<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ravi" name="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases" tests="5" failures="1" timestamp="23 Nov 2019 08:45:28 GMT" time="70.554" errors="0">
  <testcase name="invalid_invalid_credentials" time="1.106" classname="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases"/>
  <testcase name="verify_all_links" time="52.965" classname="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases.verify_all_links(OHT01_orange_hrm_ess_login_testcases.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_all_links -->
  <testcase name="invalid_valid_credentials" time="1.518" classname="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases"/>
  <testcase name="valid_invalid_credentials" time="2.071" classname="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases"/>
  <testcase name="login_using_ess_credentials" time="12.894" classname="com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases"/>
</testsuite> <!-- com.orange.hrm.ess.module.testcase.OHT01_orange_hrm_ess_login_testcases -->
